### ISSUE TITLE
Issue when BLAST return no hits

### ISSUE THREAD

**Issue by dwilkin799** [Papos92/ecoli_serotyper#1]
Great idea for a program, much more accessible than the alternatives for Ecoli serotyping.
I got the following using multi_serotyper.py
This happens when it gets about half way through my list of genomes that I want to type. Until this point the output files look exactly like what you would expect.

I'm assuming that this happens because BLAST finds no hits, and so there is a missing file...

Traceback (most recent call last):
  File "/home/david/genomics_programs/ecoli_serotyper//ecoli_serotyper.py", line 187, in <module>
    main()
  File "/home/david/genomics_programs/ecoli_serotyper//ecoli_serotyper.py", line 178, in main
    antigen = parse_blastn_output(outdir+"/blastn_results_"+type+".txt", os.environ['SERO_REF']+"/"+type.replace("type", "database")+"/"+type, log)
  File "/home/david/genomics_programs/ecoli_serotyper//ecoli_serotyper.py", line 142, in parse_blastn_output
    hit_score[hit] = int(hit.split("\t")[10])
ValueError: invalid literal for int() with base 10: '0.0'
Traceback (most recent call last):
  File "/home/david/genomics_programs/ecoli_serotyper/multi_serotyper.py", line 159, in <module>
    main()
  File "/home/david/genomics_programs/ecoli_serotyper/multi_serotyper.py", line 149, in main
    H, O = parse_logfile(out_path+"/ecoli_serotyper.log")
  File "/home/david/genomics_programs/ecoli_serotyper/multi_serotyper.py", line 106, in parse_logfile
    with open(filepath,  "r") as logfile:
IOError: [Errno 2] No such file or directory: '/media/sf_ShareFolders/Downloaded_Genomes/Escherischia/refseq/out/GCF_900195535.1_F1_366A_genomic_ecoli_serotyper_output/ecoli_serotyper.log'

**Comment by tom-van-wijk** [comment]
Dear dwilkin,

Thank you for your interest in using my tool and sorry that it took me some time to figure out and resolve this issue.

It seemes this issue occurred when multiple BLAST hits made it past all filters, meaning when multiple different O or H genes are present in the genome, this is rare.

However, with the update from today should fix the error that you got when using Multi_serotyper.
If you encounter more problems, please let me know.

Thank you
Cheers.
